services:
  - type: web
    name: mini-kanban-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma db push && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
